spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
mybatis-plus:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: false
  check-config-location: false
debug: true
logging:
  path: ./logs
  level:
    com.bzdnet.learn.springboot.dao: debug
